### ISSUE TITLE
Misleading extension for a file in the signature and attestation payloads

### ISSUE THREAD

**Issue by toddysm** [sigstore/cosign#2403] opened 2022-11-02 15:49 UTC
**Description**

Pulling the signature artifact and unzipping the layer shows the following files inside

```
$ ls -al
total 20
drwxrwxr-x 2 toddysm toddysm 4096 Oct 14 10:08 .
drwxrwxr-x 3 toddysm toddysm 4096 Oct 14 10:07 ..
-rw-r--r-- 1 toddysm toddysm  272 Dec 31  1969 09b3e371137191b52fdd07bdf115824b2b297a2003882e68d68d66d0d35fe1fc.tar.gz
-rw-r--r-- 1 toddysm toddysm  319 Dec 31  1969 manifest.json
-rw-r--r-- 1 toddysm toddysm  248 Dec 31  1969 sha256:00ce5fed483997c24aa0834081ab1960283ee9b2c9d46912bbccc3f9d18e335d
```
Trying to unzip the inner tarball gives the following error:
```
$ tar -xvf 09b3e371137191b52fdd07bdf115824b2b297a2003882e68d68d66d0d35fe1fc.tar.gz 
tar: This does not look like a tar archive
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

It seems all the files are some kind of JSON. I have two concerns with this:
- First, why does a JSON file has a `tar.gz` extension? This is misleading and may get flagged as a malicious file?
- What is the purpose of those files, considering that the signature seems to be an annotation in the manifest?

A similar structure is built for the attestations.

**Version**

1.13.0

**Comment by dlorenc** [comment] 2022-11-03 14:12
> It seems all the files are some kind of JSON. I have two concerns with this:
> 
> * First, why does a JSON file has a `tar.gz` extension? This is misleading and may get flagged as a malicious file?

IIUC this is because the Docker on-disk format for images (used by crane pull) and the registry formats are not actually the same. The docker on disk format is really only used for downloading runnable images and then loading them into docker with docker load, so the format doesn't support anything other than layer tarballs. Pulling an OCI artifact that's not a container image into a docker-formatted archive isn't really well-defined behavior.

**Comment by znewman01** [comment] 2022-11-22 18:50
I think I'm going to close this one out, because there's nothing really to be done here—this is just an artifact of the (ab)use of an OCI registry for storing non-OCI-image data, and it shouldn't impact users of Cosign directly.

If you'd like more details on what's happening here, check out the [signature spec](https://github.com/sigstore/cosign/blob/8f665771dc246b17413fef13bb32873cf3e0229b/specs/SIGNATURE_SPEC.md).

**Closed by znewman01** 2022-11-22 18:50 UTC
Labels: bug, oci

**Comment by toddysm** [comment] 2022-11-24 17:10
Thanks @znewman01! I think I have enough information and agree with closing it. Will update the information on my side.

**Comment by dlorenc** [comment] 2022-11-24 18:59
> I think I'm going to close this one out, because there's nothing really to be done here—this is just an artifact of the (ab)use of an OCI registry for storing non-OCI-image data, and it shouldn't impact users of Cosign directly.

Technically I don't think this is the issue - the issue is the abuse of a tool (`crane`) designed for working with OCI image data to download something that's not an OCI image into a format specific to OCI images. Even with the new registry APIs the `crane pull` command would have to choose between erroring or downloading into this format.
