### ISSUE TITLE
`cosign attest` doesn't work with provenances

### ISSUE THREAD

**Issue by upodroid** [sigstore/cosign#2354] opened 2022-10-18 21:50 UTC
**Description**

Hi

I'm doing provenance generation for knative and I'm seeing bugs with `cosign attest`

https://github.com/knative/test-infra/issues/3440

```
COSIGN_EXPERIMENTAL=1 cosign attest --recursive --identity-token="${ID_TOKEN}" --predicate=kn-attestation.json --type=slsaprovenance --no-tlog-upload --no-upload $(cat pkg/testdata/image-refs.txt)

Generating ephemeral keys...
Retrieving signed certificate...

        Note that there may be personally identifiable information associated with this signed artifact.
        This may include the email address associated with the account with which you authenticate.
        This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later.
Successfully verified SCT...
Using payload from: kn-attestation.json
Error: signing gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256:bac158dfb0c73d13ed42266ba287f1a86192c0ba581e23fbe012d30a1c34837c: provenance predicate: required field builder missing
main.go:62: error during command execution: signing gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256:bac158dfb0c73d13ed42266ba287f1a86192c0ba581e23fbe012d30a1c34837c: provenance predicate: required field builder missing
 ```
https://prow.knative.dev/view/gs/knative-prow/logs/nightly_net-contour_main_periodic/1582299938572734464 look for "Using payload from: attestation.json"

Builder is definitely there so is this a bug in cosign?

https://github.com/knative/test-infra/blob/main/tools/provenance-generator/kn-attestation.json

I wrote a tool to generate the provenance in the same folder as the sample attestation that I attached.

**Version**

1.13.0

**Comment by asraa** [comment] 2022-10-25 14:57
Hey! Try sending just the predicate part of the `kn-attestation.json`. Then it should work.

Like:
```
{
    "builder": {
      "id": "https://prow.knative.dev"
    },
    "buildType": "https://prow.knative.dev/ProwJob@v1",
    "invocation": {
      "configSource": {
        "entryPoint": "https://github.com/knative/test-infra/main/hack/release.sh"
      }
    },
    "buildConfig": {
      "command": [
        "runner.sh",
        "./hack/release.sh",
        "--publish",
        "--tag-release"
      ],
      "entrypoint": {
        "timeout": 10800000000000,
        "grace_period": 15000000000,
        "artifact_dir": "/logs/artifacts",
        "args": [
          "runner.sh",
          "./hack/release.sh",
          "--publish",
          "--tag-release"
        ],
        "container_name": "test",
        "process_log": "/logs/process-log.txt",
        "marker_file": "/logs/marker-file.txt",
        "metadata_file": "/logs/artifacts/metadata.json"
      },
      "prowjob": {
        "metadata": {
          "name": "b71fa037-0d8c-11ed-ab62-2ace146f4dd8",
          "namespace": "default",
          "uid": "dc818b0b-df93-44a8-86fe-fee9c02182a0",
          "resourceVersion": "71593618",
          "generation": 7,
          "creationTimestamp": "2022-07-27T09:15:53Z",
          "labels": {
            "created-by-prow": "true",
            "prow.k8s.io/build-id": "1552221225705541632",
            "prow.k8s.io/context": "",
            "prow.k8s.io/id": "b71fa037-0d8c-11ed-ab62-2ace146f4dd8",
            "prow.k8s.io/job": "nightly_serving_main_periodic",
            "prow.k8s.io/refs.base_ref": "main",
            "prow.k8s.io/refs.org": "knative",
            "prow.k8s.io/refs.repo": "serving",
            "prow.k8s.io/type": "periodic"
          },
          "annotations": {
            "prow.k8s.io/context": "",
            "prow.k8s.io/job": "nightly_serving_main_periodic",
            "testgrid-dashboards": "serving",
            "testgrid-tab-name": "nightly"
          }
        },
        "spec": {
          "type": "periodic",
          "agent": "kubernetes",
          "cluster": "prow-build",
          "namespace": "test-pods",
          "job": "nightly_serving_main_periodic",
          "extra_refs": [
            {
              "org": "knative",
              "repo": "serving",
              "base_ref": "main",
              "path_alias": "knative.dev/serving"
            }
          ],
          "report": true,
          "pod_spec": {
            "volumes": [
              {
                "name": "docker-graph",
                "emptyDir": {}
              },
              {
                "name": "modules",
                "hostPath": {
                  "path": "/lib/modules",
                  "type": "Directory"
                }
              },
              {
                "name": "cgroup",
                "hostPath": {
                  "path": "/sys/fs/cgroup",
                  "type": "Directory"
                }
              },
              {
                "name": "nightly-account",
                "secret": {
                  "secretName": "prow-google-credentials",
                  "items": [
                    {
                      "key": "nightly.json",
                      "path": "service-account.json"
                    }
                  ]
                }
              }
            ],
            "containers": [
              {
                "name": "",
                "image": "gcr.io/knative-tests/test-infra/prow-tests:v20220725-a4aaff33",
                "command": [
                  "runner.sh",
                  "./hack/release.sh",
                  "--publish",
                  "--tag-release"
                ],
                "env": [
                  {
                    "name": "DOCKER_IN_DOCKER_ENABLED",
                    "value": "true"
                  },
                  {
                    "name": "GOOGLE_APPLICATION_CREDENTIALS",
                    "value": "/etc/nightly-account/service-account.json"
                  }
                ],
                "resources": {
                  "limits": {
                    "memory": "16Gi"
                  },
                  "requests": {
                    "memory": "12Gi"
                  }
                },
                "volumeMounts": [
                  {
                    "name": "docker-graph",
                    "mountPath": "/docker-graph"
                  },
                  {
                    "name": "modules",
                    "mountPath": "/lib/modules"
                  },
                  {
                    "name": "cgroup",
                    "mountPath": "/sys/fs/cgroup"
                  },
                  {
                    "name": "nightly-account",
                    "readOnly": true,
                    "mountPath": "/etc/nightly-account"
                  }
                ],
                "securityContext": {
                  "privileged": true
                }
              }
            ],
            "nodeSelector": {
              "type": "testing"
            }
          },
          "decoration_config": {
            "timeout": "3h0m0s",
            "grace_period": "15s",
            "utility_images": {
              "clonerefs": "gcr.io/k8s-prow/clonerefs:v20220721-cf42b99a12",
              "initupload": "gcr.io/k8s-prow/initupload:v20220721-cf42b99a12",
              "entrypoint": "gcr.io/k8s-prow/entrypoint:v20220721-cf42b99a12",
              "sidecar": "gcr.io/k8s-prow/sidecar:v20220721-cf42b99a12"
            },
            "resources": {
              "sidecar": {
                "requests": {
                  "cpu": "100m",
                  "memory": "20Mi"
                }
              }
            },
            "gcs_configuration": {
              "bucket": "knative-prow",
              "path_strategy": "explicit"
            },
            "gcs_credentials_secret": "gcs-upload"
          },
          "reporter_config": {
            "slack": {
              "channel": "serving",
              "job_states_to_report": [
                "failure"
              ],
              "report_template": "\"The nightly release job fails, check the log: <{{.Status.URL}}|View logs>\"\n",
              "report": true
            }
          },
          "prowjob_defaults": {
            "tenant_id": "GlobalDefaultID"
          }
        },
        "status": {
          "startTime": "2022-07-27T09:15:53Z",
          "pendingTime": "2022-07-27T09:15:53Z",
          "completionTime": "2022-07-27T11:15:41Z",
          "state": "success",
          "description": "Job succeeded.",
          "url": "https://prow.knative.dev/view/gs/knative-prow/logs/nightly_serving_main_periodic/1552221225705541632",
          "pod_name": "b71fa037-0d8c-11ed-ab62-2ace146f4dd8",
          "build_id": "1552221225705541632",
          "prev_report_states": {
            "gcsk8sreporter": "success",
            "gcsreporter": "success"
          }
        }
      }
    },
    "metadata": {
      "buildInvocationID": "1552221225705541632",
      "buildStartedOn": "2022-07-27T12:15:53+03:00",
      "buildFinishedOn": "2022-07-27T14:15:41+03:00",
      "completeness": {
        "parameters": true,
        "environment": true,
        "materials": true
      },
      "reproducible": false
    },
    "materials": [
      {
        "uri": "git+https://github.com/knative/serving",
        "digest": {
          "sha1": "c82be271867f137d0923be34acd18b6aca452446"
        }
      }
    ]
  
  }
```

The cosign tool creates the rest, but unfortunately I think that it MIGHT create the subjects individually per-image.

**Comment by znewman01** [comment] 2022-11-02 13:14
I'm going to mark this a duplicate of https://github.com/sigstore/cosign/issues/2394

(I know this issue came first but there's already a little more discussion there.)

**Closed by znewman01** 2022-11-02 13:14 UTC
Labels: bug
