### ISSUE TITLE
cosign cli doesn't recognize `.../cryptoKeyVersions/$KEY_VERSION`

### ISSUE THREAD

**Issue by chuangw6** [sigstore/cosign#2094] opened 2022-07-22 18:27 UTC
I want to use cosign cli to verify a signature that was generated using `sigstore` pkg with a gcp kms ref `gcpkms://projects/$PROJECT/locations/$LOCATION/keyRings/$KEYRING/cryptoKeys/$KEY/cryptoKeyVersions/$KEY_VERSION`.

```
export KEY_REF=gcpkms://projects/chuangw-test/locations/global/keyRings/test/cryptoKeys/mykey/cryptoKeyVersions/1
cosign verify-blob --key $KEY_REF --signature signature signature
```
However, I got an error.
```
Error: verifying blob [signature]: loading public key: open gcpkms:/projects/chuangw-test/locations/global/keyRings/test/cryptoKeys/mykey/cryptoKeyVersions/1: no such file or directory
main.go:46: error during command execution: verifying blob [signature]: loading public key: open gcpkms:/projects/chuangw-test/locations/global/keyRings/test/cryptoKeys/mykey/cryptoKeyVersions/1: no such file or directory
```

If I changed the `KEY_REF` from `.../cryptoKeyVersions/1` to `.../versions/1`, the cli verification works. If the version part `/cryptoKeyVersions/1` is completely removed from the `KEY_REF`, the cli verification also works.

I am wondering if the verification with `../cryptoKeyVersions/$KEY_VERSION` is intentionally not supported by cosign cli or it is a bug.
Thanks!

**Comment by haydentherapper** [comment] 2022-08-02 19:59
I see in the error output it's prefixed with `gcpkms:/` instead of `gcpkms://`. If you add an extra slash, do you still get the error?

**Comment by chuangw6** [comment] 2022-08-02 20:38
> I see in the error output it's prefixed with `gcpkms:/` instead of `gcpkms://`. If you add an extra slash, do you still get the error?

Hi @haydentherapper , 

The key ref in the `cosign verify-blob --key` starts with `gcpkms://` rather than `gcpkms:/`. Don't know why in the error it complains`gcpkms:/`.

**Comment by chuangw6** [comment] 2022-08-03 21:04
To summarize working v.s. not-working key ref for signing & verification 

> For verification, `cosign verify-blob --key $KEY_REF --signature ...` is used.


1. no version specified
 `gcpkms://projects/$PROJECT/locations/$LOCATION/keyRings/$KEYRING/cryptoKeys/$KEY`
✅  works for signing
✅  works for verification

2. version specified using `cryptoKeyVersions`
 `gcpkms://projects/$PROJECT/locations/$LOCATION/keyRings/$KEYRING/cryptoKeys/$KEY/cryptoKeyVersions/$KEY_VERSION`
✅ works for signing
❌ doesn't works for cosign verification 

3. version specified using `versions`
`gcpkms://projects/$PROJECT/locations/$LOCATION/keyRings/$KEYRING/cryptoKeys/$KEY/versions/$KEY_VERSION`
✅  works for signing
✅  works for verification

**Comment by haydentherapper** [comment] 2022-08-04 18:43
cc @cdris

**Comment by wlynch** [comment] 2022-08-18 14:30
@chuangw6 what version of cosign are you using?

I think https://github.com/sigstore/sigstore/commit/21bce79303a006ad3abd26c368ba3946061d6679 fixes this, and was added to cosign in v0.10.0

The `gcpkms:/` behavior looks like cosign trying to interpret the string as a file path after the GCP KMS regex didn't match.

**Comment by znewman01** [comment] 2022-09-03 00:56
I think this is a bad error message; see https://github.com/sigstore/cosign/pull/2220

**Comment by znewman01** [comment] 2022-09-04 21:57
I'm closing this, as I believe between #2220 (better error message) and https://github.com/sigstore/sigstore/pull/359 the issue is resolved. Please reopen if you're seeing this again.

**Closed by znewman01** 2022-09-04 21:57 UTC
Labels: question
