### ISSUE TITLE
Implement standardized Outputs (exit codes)

### ISSUE THREAD

**Issue by xopham** [sigstore/cosign#2742] opened 2023-02-24 03:17 UTC
**Description**
Imho, cosign tends to produce confusing output to stdout and stderr. There seems occur a mixture of both in some cases. When failing, the output often appears "unhandled" such as the following:
```bash
Error: no matching signatures:
  signature not found in transparency log
  main.go:62: error during command execution: no matching signatures:
  signature not found in transparency log
```
This is not only hard to interpret as a human, it moreover complicates integration with other tools because the output needs to be parsed and interpreted and as it has not been strictly defined in the past it change throughout the versions.

**How to resolve?**
Besides returning proper error messages for readability, defining exit codes would simplify integration with other tools. At [Connaisseur](https://github.com/sse-secure-systems/connaisseur), we have been struggling to parse the "unhandled" errors.

**Comment by znewman01** [comment] 2023-02-27 14:26
Duplicate of https://github.com/sigstore/cosign/issues/948 and https://github.com/sigstore/cosign/issues/2510

**Closed by znewman01** 2023-02-27 14:26 UTC
Labels: duplicate, enhancement
