### ISSUE TITLE
inconsistent behavior when signing  container

### ISSUE THREAD

**Issue by capri-xiyue** [sigstore/cosign#1771] opened 2022-04-18 16:47 UTC
**Description**
The behavior is different when you use ` cosign sign --key xxx us-docker.pkg.dev/$PROJECT/$REPO/my-image `(signature will get appended, `xxx.sig` records all signatures) and ` cosign sign --key xxx us-docker.pkg.dev/$PROJECT/$REPO/my-image:sha256@xxx `(signature will get overridden, `xxx.sig` only records the latest one). 

But for `cosign attest`, it will always append attestations to `xxx.att` and `xxx.att` records all attestation no matter I use `us-docker.pkg.dev/$PROJECT/$REPO/my-image` or `us-docker.pkg.dev/$PROJECT/$REPO/my-image:sha256@xxx`.

Is this a bug in `cosign sign`?

**Comment by wlynch** [comment] 2022-04-18 20:16
This sounds very similar to https://github.com/sigstore/cosign/issues/1654.

Will do a bit more digging before I mark this as a dupe.

**Comment by capri-xiyue** [comment] 2022-04-18 20:30
> This sounds very similar to #1654.
> 
> Will do a bit more digging before I mark this as a dupe.

I think I use  key-full signing instead of the keyless signing in  #1654.

**Comment by wlynch** [comment] 2022-04-18 20:49
What version of cosign did you notice this in? 👀

**Comment by capri-xiyue** [comment] 2022-05-16 20:31
> What version of cosign did you notice this in? 👀

1.5.2

**Comment by znewman01** [comment] 2022-11-22 19:55
> > What version of cosign did you notice this in? 👀
> 
> 1.5.2

If I had to guess, this is probably fixed in 1.7+. Can you reproduce?

(Sorry for the long delay)

**Comment by haydentherapper** [comment] 2024-01-06 00:38
Closing as outdated

**Closed by haydentherapper** 2024-01-06 00:38 UTC
Labels: bug, oci
