### ISSUE TITLE
go install  fail with error

### ISSUE THREAD

**Issue by xmlking** [sigstore/cosign#1667] opened 2022-03-27 00:03 UTC
go install github.com/sigstore/cosign/cmd/cosign@latest                                                                
go: github.com/sigstore/cosign/cmd/cosign@latest (in github.com/sigstore/cosign@v1.6.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.

Env
 go version                                                                                                                                                                                                  
go version go1.18 darwin/arm64

MacOS 12.3

**Comment by dlorenc** [comment] 2022-03-27 00:28
This looks like a duplicate of https://github.com/sigstore/cosign/issues/1555

**Comment by cpanato** [comment] 2022-03-28 07:04
yep, will close this one

**Closed by cpanato** 2022-03-28 07:04 UTC
Labels: bug
