### ISSUE TITLE
OCI manifest created timestamp wrong with v2.2.0

### ISSUE THREAD

**Issue by baal-lgln** [sigstore/cosign#3298] opened 2023-10-12 15:14 UTC
**Description**

We are using a cosign container inside our pipeline to sign newly build images. 
Up until v2.1.1 (public.ecr.aws/bitnami/cosign:2.1.1) this works without problems:
`cosign sign --yes --key cosign.key {{image}}@sha256:{{digest}}`
That creates a new OCI entry inside our IBM Container Registry:
```json
{
  "Id": "sha256:[...]",
  "Parent": "",
  "Comment": "",
  "Created": "2023-10-12T14:52:17.989015938Z",
[...]
  "Size": 251,
  "VirtualSize": 251,
  "RootFS": {
    "Type": "layers",
    "Layers": [
      "sha256:[...]"
    ]
  },
  "ManifestType": "application/vnd.oci.image.manifest.v1+json"
}
```
After updating to v2.2.0 (public.ecr.aws/bitnami/cosign:2.2.0) the **Created** timestamp is totally wrong and leads to this:
```json
{
  "Id": "sha256:[...]",
  "Parent": "",
  "Comment": "",
  "Created": "0001-01-01T00:00:00Z",
 [...]
  "Size": 251,
  "VirtualSize": 251,
  "RootFS": {
    "Type": "layers",
    "Layers": [
      "sha256:[...]"
    ]
  },
  "ManifestType": "application/vnd.oci.image.manifest.v1+json"
}
```

As we have some rules to delete older entries inside our registry these signatures are deleted soon after creation.
Image can be verified with `cosign verify` in both cases. The output does not differ.
This can be reproduced with different images.

**Version**

`public.ecr.aws/bitnami/cosign:2.2.0`

**Comment by ztcjoe93** [comment] 2023-10-16 03:38
I encountered this issue some time back and dug into it for a bit -- this is part of a [commit](https://github.com/sigstore/cosign/pull/3121) that reverts a [previous implementation](https://github.com/sigstore/cosign/pull/2108) to ensure that the produced artifacts are deterministic, which is pushed out in `2.2.0` as part of the milestones.

I believe container registries that uses timestamp as a housekeeping rule (i.e GitLab, GCR) will be affected since effectively the signatures are deleted after creation. No clue on any alternative workarounds, but personally I pinned the version to `2.1.1` for the time being to mitigate this.

**Comment by haydentherapper** [comment] 2023-10-16 05:47
@jonjohnsonjr did you want to chime in on this?
To my knowledge, this is done so that container builds are reproducible.

**Comment by avasile8709** [comment] 2023-10-17 13:43
Hello,

I have the same issue here, using GitLab pipeline. 

![image](https://github.com/sigstore/cosign/assets/123961371/f9258fd2-cac8-461b-9477-eaaae2a180a6)

Do you have any new information about this issue?

**Comment by uwevanheesch** [comment] 2023-10-30 12:45
Same here.

**Comment by uwevanheesch** [comment] 2023-10-30 12:46
We encounter the same error in Gitlab.

**Comment by Lerentis** [comment] 2023-11-07 20:49
kind of a bummer to write here again for the same reason :/ 
this effectively blocks anyone who is using housekeeping jobs to update to any release after 2.1. 
imo a very big sacrifice for a gain that is rather theoretical. if there is no workaround available i would suggest to reconsider this decision @jonjohnsonjr

**Comment by dheeg** [comment] 2024-01-02 14:05
@cpanato 

We encountered the same issue back in 2022. Then https://github.com/sigstore/cosign/pull/2108 was merged in order to fix the issue for GitLab users with automated registry cleanup rules.

Now https://github.com/sigstore/cosign/pull/3121 was merged which reverts the fix and is itself flagged as "fix".

* I only see one issue (https://github.com/sigstore/cosign/issues/3120) which was written by the same person which also created the PR. Did customers/users ask for this "fix"? To me it looks like more users are asking for the opposite.
* Was there a strategic decision made? There are clearly pros and cons for both solutions and the merged PR doesn't contain any substantial discussion, more an single opinion.

**Closed** 2024-03-07 23:02 UTC
Labels: bug

**Comment by baal-lgln** [comment] 2024-07-23 09:29
v2.3.0 was just released (public.ecr.aws/bitnami/cosign:2.3.0-debian-12-r0) and sadly nothing has changed. This is still a huge problem for us.

**Comment by bobcallaway** [comment] 2024-07-23 11:26
> v2.3.0 was just released (public.ecr.aws/bitnami/cosign:2.3.0-debian-12-r0) and sadly nothing has changed. This is still a huge problem for us.

Did you use the new command line argument?

 --honor-create-timestamp

**Comment by baal-lgln** [comment] 2024-07-23 12:41
--honor-create-timestamp does not exist for cosign sign, seems to be the  --record-creation-timestamp flag. With `cosign sign --record-creation-timestamp=true` it finally works 👍  

Would be great to have this kind of change added to the changelog (at least I couldn't find it).
