### ISSUE TITLE
OCI Artifacts to store signatures

### ISSUE THREAD

**Issue by loresuso** [sigstore/cosign#2417] opened 2022-11-07 14:56 UTC
**Question**

Hello everybody,

Now that also docker has introduced [support for OCI artifacts](https://www.docker.com/blog/announcing-docker-hub-oci-artifacts-support/), I would like to know if there is an ongoing effort to store signatures as such, using the latest changes deriving from the work done by the [Reference Types Working Group](https://github.com/opencontainers/wg-reference-types/), who introduced `subject` field and `referrers api` to properly implement artifacts that refers to other ones like signatures.
I am seeing that also go-containerregistry is [working on something](https://github.com/google/go-containerregistry/pull/1455), so maybe `cosign` could use it when it's done

Thank you!

**Comment by dlorenc** [comment] 2022-11-07 15:10
cc @jdolitsky @imjasonh 

We should be able to switch to storing signatures as OCI artifacts whenever now that Dockerhub has added support.

We're also planning to switch to the new reference types API and are prototyping it now!

**Comment by znewman01** [comment] 2022-11-07 18:44
Duplicate of https://github.com/sigstore/cosign/issues/1397

**Closed by znewman01** 2022-11-07 18:44 UTC
Labels: question
