### ISSUE TITLE
tag update race

### ISSUE THREAD

**Issue by cppforlife** [sigstore/cosign#9] opened 2021-02-09 23:19 UTC
are yall aware of any work in opencontainers to support atomic tag swaps (aka fail to update tag if expected previous digest does not match what tag is pointing at right before the update)? it might be too much burden to implement for registry implementors but would be handy for tag updates.

**Comment by dlorenc** [comment] 2021-02-10 00:16
> are yall aware of any work in opencontainers to support atomic tag swaps (aka fail to update tag if expected previous digest does not match what tag is pointing at right before the update)? it might be too much burden to implement for registry implementors but would be handy for tag updates.

I think there's a discussion to something with HTTP etags for this. @jonjohnsonjr knows more!

**Comment by jonjohnsonjr** [comment] 2021-02-10 00:43
Yes, I proposed a solution for this in last week's OCI dev call. It's on my TODO list to put together an actual PR to the spec.

Everyone seemed generally receptive to the idea, so I have high hopes for this getting implemented broadly. I'll ping this issue when I open the PR.

**Comment by jonjohnsonjr** [comment] 2021-03-13 00:09
As promised @cppforlife https://github.com/opencontainers/distribution-spec/pull/251

**Comment by znewman01** [comment] 2022-11-22 20:15
Duplicate of https://github.com/sigstore/cosign/issues/2432

**Closed by znewman01** 2022-11-22 20:15 UTC
Labels: enhancement
