### ISSUE TITLE
passing '--bundle' flag causes cosign to ignore '--output-certificate' and '--output-signature'

### ISSUE THREAD

**Issue by patflynn** [sigstore/cosign#2005] opened 2022-06-17 17:42 UTC
Good news is this behavior is the same in keyless and keyfull mode. 

to reproduce:
1) run ` COSIGN_EXPERIMENTAL=true cosign sign-blob java-service.jar --output-certificate foo.pem --output-signature foo.sig --bundle foo.bundle`
2. run `$ ls `and observe that your foo.sig and foo.pem files were never written.

**Comment by znewman01** [comment] 2022-06-17 19:19
Duplicate of #1821

**Comment by Dentrax** [comment] 2022-06-19 19:58
I think @priyawadhwa did this on purpose, since `foo.bundle` contains both of `sig` and `cert` information inside it:

```
# same output as --output-signature
$ cat foo.bundle | jq -r .base64Signature

# same output as --output-certificate
$ cat foo.bundle | jq -r .cert
```

What's the right UX here?

* if `--bundle` passed with any other `--output-` flag, should we print an info log about we ignore other outputs?
* rename `--bundle` to `--output-bundle` and do not ignore the rest
* make `--bundle` mutually exclusive with `--output-` flags

**Comment by priyawadhwa** [comment] 2022-06-20 14:42
Just commented in #1821 as well, but I think this is a bug. `--bundle` should work independently & `--output-signature` and `--output-certificate` should be respected!

**Closed** 2022-06-23 12:22 UTC
Labels: bug
