### ISSUE TITLE
Local Cert verify not working for Azure KMS

### ISSUE THREAD

**Issue by containerpope** [sigstore/cosign#589] opened 2021-08-28 09:04 UTC
**Description**

Using cosign with Azure KMS results in different behavior for validation with KMS and local pub cert.

```sh
cosign verify -key azurekms://keyvault-xyz.vault.azure.net/cosign registryXYZ.azurecr.io/example-func:1.0.0
using embedded fulcio certificate. did you run `cosign init`? error retrieving target:  missing target metadata: tuf: no root keys found in local meta store

Verification for registryXYZ.azurecr.io/example-func:1.0.0 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - The signatures were verified against the specified public key
  - Any certificates were verified against the Fulcio roots.

[{"critical":{"identity":{"docker-reference":"registryXYZ.azurecr.io/example-func"},"image":{"docker-manifest-digest":"sha256:e231349fdf394a570e0cb84fe5109bc6980f52b84dd219fcae9922922a715d7d"},"type":"cosign container image signature"},"optional":{"tag":"1.0.0"}},{"critical":{"identity":{"docker-reference":"registryXYZ.azurecr.io/example-func"},"image":{"docker-manifest-digest":"sha256:e231349fdf394a570e0cb84fe5109bc6980f52b84dd219fcae9922922a715d7d"},"type":"cosign container image signature"},"optional":null}]
```

But when I use the created public certificate, the result is as follows:

```sh
cosign verify -key cosign.pub registryXYZ.azurecr.io/example-func:1.0.0
using embedded fulcio certificate. did you run `cosign init`? error retrieving target:  missing target metadata: tuf: no root keys found in local meta store
error: no matching signatures:
failed to verify signature
 failed to verify signature
```

I also exported the key again and tried to reproduce, with the same result:

```sh
cosign public-key -key azurekms://ckeyvaultXYZ.azure.net/cosign > cosign-new.pub
cosign verify -key cosign-new.pub registryXYZ.azurecr.io/example-func:1.0.0
using embedded fulcio certificate. did you run `cosign init`? error retrieving target:  missing target metadata: tuf: no root keys found in local meta store
error: no matching signatures:
failed to verify signature
 failed to verify signature
```

Is there anything I did wrong or is there a bug in the verification? Earlier I added also some comments to #399, when the feature was still under active development. 

```sh
cosign version
GitVersion:    v1.1.0
GitCommit:     67934a685ddc83aa7b0b8a55c911e299117afac5
GitTreeState:  clean
BuildDate:     '2021-08-25T21:51:14Z'
GoVersion:     go1.17
Compiler:      gc
Platform:      darwin/arm64
```

**Comment by dlorenc** [comment] 2021-08-28 12:37
Thanks for the report! When we've seen this in the past, it's usually because the KMS key gets created with a different algorithm from what cosign is expecting. What hash and signature algorithm are you using, and how did you create the azure key?

**Comment by cpanato** [comment] 2021-08-28 13:01
I will try to reproduce and identify what is the issue. But if you can provide more information will be good as well

/assign

**Comment by containerpope** [comment] 2021-08-29 06:09
@dlorenc @cpanato 

thank you for getting back to me, here are some more details:

![CleanShot 2021-08-29 at 08 06 22](https://user-images.githubusercontent.com/12080409/131240518-314bde83-a1a0-4b5f-b013-3061baad9bc9.png)

I created the azure key with the built in cosign command.

```sh
cosign generate-key-pair -kms azurekms://keyvaultXYZ.vault.azure.net/cosign
```

The interesting part is, that the verify via the KMS command works, while using the local public key does not work.

**Comment by containerpope** [comment] 2021-10-30 07:43
@dlorenc @cpanato can you give me some details on which sections of the code to look into for this? We have all the environment setup, maybe we can troubleshoot it and send a PR :)

**Comment by mwielgoszewski** [comment] 2021-11-04 14:56
The signature returned by KeyVault is the ECDSA {R,S} values concatenated as bytes. Digging through the code, [co.SigVerifier.VerifySignature()](https://github.com/sigstore/cosign/blob/main/pkg/cosign/verify.go#L175) calls [ecdsa.VerifyASN1()](https://github.com/sigstore/sigstore/blob/9a93316efcab066173677cbc7b8cad9d25b901e8/pkg/signature/ecdsa.go#L168), defined in [ecdsa.go](https://github.com/golang/go/blob/master/src/crypto/ecdsa/ecdsa.go#L339) which expects the signature to be formatted as an ASN.1 sequence of integers, as defined in [rfc3279 #section-2.2.3](https://datatracker.ietf.org/doc/html/rfc3279#section-2.2.3), otherwise it returns false:

> ECDSA-Sig-Value ::= SEQUENCE { r INTEGER, s INTEGER }

If convert the signature to an ASN.1 sequence, and manually extract the digest from the manifest, I can successfully verify with openssl (see this [gist](https://gist.github.com/mwielgoszewski/19cead4d36e835fcb53eb107a54d7a38) to reproduce):

```
% openssl dgst -sha256 -verify cosign.pub -signature cosign.signature cosign.digest
Verified OK
```

Interestingly, note the `-sha256` in the openssl command above. In trying to get signature to verify by calling KeyVault's Key Sign API, I had to hash the digest a second time. See this [Python script](https://gist.github.com/mwielgoszewski/5cd70537cd7128839454f27eea4cb961) for some test code, in particular:

```
digest = hashlib.sha256(args.payload.read()).digest()
```

where `args.payload` is the digest bytes from the cosign produced signature manifest. This seems to indicate there's some double hashing going on. I'm not certain how those digest bytes are computed to begin with - is there a specification (or reference inputs/outputs) that details how to compute a manifest, digest, and signature for a given artifact? I can't figure out how the digest that's being signed was computed.

**Comment by dlorenc** [comment] 2021-11-04 15:06
> double hashing going

Ah thanks! I actually found this at one point and had a patch to fix it but never got it out! I'll give this all a try!

**Comment by containerpope** [comment] 2021-11-04 15:32
@dlorenc if you have something to test, feel free to reach out, I still have my running test setup here :)

**Comment by dlorenc** [comment] 2021-11-06 20:16
I think I got the double hash here: https://github.com/sigstore/sigstore/pull/126

Kind of hard to test until we get it merged since you'd need to pull this down and do a local replace directive in the cosign go.mod :(

**Comment by dlorenc** [comment] 2021-11-06 20:57
Whoo! I've verified that this works now with https://github.com/sigstore/sigstore/pull/126

**Comment by dlorenc** [comment] 2021-11-07 23:50
@containerpope this should be fixed now! Please let me know if you get a chance to try it out!

**Closed** 2021-11-07 23:49 UTC

**Comment by containerpope** [comment] 2021-11-08 06:45
@dlorenc it works like a charm, after I signed my testcontainer again, thanks alot :) 
Will there be a release soon or should I just take the main branch for now?

**Comment by dlorenc** [comment] 2021-11-08 14:35
We can probably cut a 1.3.1 this week. WDYT @dekkagaijin and @cpanato?

**Comment by cpanato** [comment] 2021-11-08 15:33
> We can probably cut a 1.3.1 this week. WDYT @dekkagaijin and @cpanato?

replied here https://sigstore.slack.com/archives/C01PZKDL4DP/p1636358489206200

but sounds a good idea

**Comment by shubham2110** [comment] 2023-09-05 17:59
It's not working for me. 

GitVersion:    v2.1.1
GitCommit:     baf97ccb4926ed09c8f204b537dc0ee77b60d043
GitTreeState:  clean
BuildDate:     2023-06-27T06:57:11Z
GoVersion:     go1.20.5
Compiler:      gc
Platform:      linux/amd64

![image](https://github.com/sigstore/cosign/assets/10593883/963a2733-c25e-4b0a-9ea4-be0a104ca131)

**Comment by shubham2110** [comment] 2023-09-05 18:00
It is still not working for me : 

GitVersion:    v2.1.1
GitCommit:     baf97ccb4926ed09c8f204b537dc0ee77b60d043
GitTreeState:  clean
BuildDate:     2023-06-27T06:57:11Z
GoVersion:     go1.20.5
Compiler:      gc
Platform:      linux/amd64
